package edu.tmpt.texttranslate;
public enum LangCode {
    AFRIKAANS ("af", "Pretoria, South Africa"),
    ALBANIAN ("sq", "Tirana, Albania"),
    ARABIC ("ar", "Tehran, Iran"),
    ARMENIAN ("hy", "Yerevan, Armenia"),
    AZERBAIJANI ("az", "Baku, Azerbaijan"),
    BASQUE ("eu", "Bilbao, Spain"),
    BELARUSIAN ("be", "Minsk, Belarus"),
    BENGALI ("bn", "Dhaka, Bangladesh"),
    BOSNIAN ("bs", "Sarajevo, Bosnia and Herzegovina"),
    BULGARIAN ("bg", "Sofia, Bulgaria"),
    CATALAN ("ca", "Madrid, Spain"),
    CEBUANO ("ceb", "Cebu City, Philippines"),
    CHINESESIM ("zh-SM", "Beijing, China"),
    CHINESETRA ("zh-TW", "Beijing, China"),
    CROATIAN ("hr", "Zagreb, Croatia"),
    CZECH ("cs", "Prague, Czech Republic"),
    DANISH ("da", "Copenhagen, Denmark"),
    DUTCH ("nl", "Amsterdam, Netherlands"),
    ENGLISH ("en", "Washington, D.C., United States of America"),
    ESPERANTO ("eo", "Canberra, Australia"),
    ESTONIAN ("et", "Tallinn, Estonia"),
    FILIPINO ("tl", "Manila, Philippines"),
    FINNISH ("fi", "Helsinki, Finland"),
    FRENCH ("fr", "Paris, France"),
    GALICIAN ("gl", "Santiago de Compostela, Spain"),
    GEORGIAN ("ka", "Tbilisi, Georgia"),
    GERMAN ("de", "Berlin, Germany"),
    GREEK ("el", "Athens, Greece"),
    GUJARATI ("gu", "Gandhinagar, India"),
    HAITIAN_CREOLE ("ht     ", "Port-au-Prince, Haiti"),
    HAUSA ("ha", "Abuja, Nigeria"),
    HEBREW ("iw", "Jerusalem, Israel"),
    HINDI ("hi", "New Delhi, India"),
    HMONG ("hmn", "Beijing, China"),
    HUNGARIAN ("hu", "Budapest, Hungary"),
    ICELANDIC ("is", "Reykjavík, Iceland"),
    IGBO ("ig", "Abuja, Nigeria"),
    INDONESIAN ("id", "Jakarta, Indonesia"),
    IRISH ("ga", "Dublin, Ireland"),
    ITALIAN ("it", "Rome, Italy"),
    JAPANESE ("ja", "Tokyo, Japan"),
    JAVANESE ("jw", "Jakarta, Indonesia"),
    KANNADA ("kn", "Bangalore, India"),
    KHMER ("km", "Phnom Penh, Cambodia"),
    KOREAN ("ko", "Seoul, South Korea"),
    LAO ("lo", "Vientiane, Laos"),
    //LATIN ("la", "Rome, Italy"),
    LATVIAN ("lv", "Riga, Latvia"),
    LITHUANIAN ("lt", "Vilnius, Lithuania"),
    MACEDONIAN ("mk", "Skopje, Republic of Macedonia"),
    MALAY ("ms", "Kuala Lumpur, Malaysia"),
    MALTESE ("mt", "Valletta, Republic of Malta"),
    MAORI ("mi", "Wellington, New Zealand"),
    MARATHI ("mr", "Mumbai, India"),
    MONGOLIAN ("mn", "Ulan Bator, Mongolia"),
    NEPALI ("ne", "Kathmandu, Nepal"),
    NORWEGIAN ("no", "Oslo, Norway"),
    PERSIAN ("fa", "Tehran, Iran"),
    POLISH ("pl", "Warsaw, Poland"),
    PORTUGESE ("pt", "Lisbon, Portugal"),
    PUNJABI ("pa", "Lahore, Pakistan"),
    ROMANIAN ("ro", "Bucharest, Romania"),
    RUSSIAN ("ru", "Moscow, Russia"),
    SERBIAN ("sr", "Belgrade, Serbia"),
    SLOVAK ("sk", "Bratislava, Slovakia"),
    SLOVENIAN ("sl", "Ljubljana, Slovenia"),
    SOMALI ("so", "Mogadishu, Somalia"),
    SPANISH ("es", "Madrid, Spain"),
    SWAHILI ("sw", "Zanzibar City, Tanzania"),
    SWEDISH ("sv", "Stockholm, Sweden"),
    TAMIL ("ta", "Colombo, Sri Lanka"),
    TELUGU ("te", "Hyderabad, India"),
    THAI ("th", "Bangkok, Thailand"),
    TURKISH ("tr", "Ankara, Turkey"),
    UKRAINIAN ("uk", "Kiev, Ukrane"),
    URDU ("ur", "Lucknow, India"),
    VIETNAMESE ("vi", "Hanoi, Vietnam"),
    WELSH ("cy", "Cardiff, Wales"),
    YIDDISH ("yi", "Jerusalem, Israel"),
    YORUBA ("yo", "Porto-Novo, Benin"),
    ZULU ("zu", "Bulawayo, Zimbabwe");
    
    String code;
    String capital;
    
    LangCode(String code, String capitol) {
            this.code = code;
            this.capital = capitol;
    }
}